import type { Metadata } from "next";
import { Geist, Geist_Mono  } from "next/font/google";
import "./globals.css";
import { NavMenu } from "./_components/NavBar/Navbar";
import { Toaster } from "@/components/ui/sonner";
import ContentProvider from "@/providers/sessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>        
        <ContentProvider>
          <NavMenu/>
          {children}
        </ContentProvider>
        <Toaster position="top-center"/>
      </body>
    </html>
  );
}
